### ISSUE TITLE
pontoon-logo.svg and bugzilla-icon.png should be listed in web_accessible_resources

### ISSUE THREAD

**Issue by Rob--W** [MikkCZ/pontoon-tools#107]
(I am not a user, but I spotted this error in an unrelated bug report at https://bugzilla.mozilla.org/show_bug.cgi?id=1548508#c37 )

Extension resources are not visible to web content by default. If you want to embed extension resources (such as images) in a web page, then they need to be added to the `web_accessible_resources` section in manifest.json - see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/web_accessible_resources

The Pontoon Tools extension references at least two images without declaring them in `web_accessible_resources`. Consequently, those images are not loaded and an error is printed to the console instead.

https://github.com/MikkCZ/pontoon-tools/blob/7a6fec72a8651216fadbf50f6e13f7881d312c05/src/packages/content-scripts/js/context-buttons.js#L19-L42

**Comment by MikkCZ** [comment]
Thank you Rob for the report.

To my best knowledge web accessible resources are for the case when the website/JS on the website want to access those. This should not be the case of Pontoon Tools, as the extension content script is using them, but I may be wrong, I am not familiar with all the cases and I never attempted to use web accessible resources.

Just the clarify the error in console was seen on GMail website? Because Pontoon Tools have no reason to be active in GMail tabs, the less the content script. Maybe @gaby2300 do you know what exact website the error in console came from?

**Comment by Rob--W** [comment]
The error was seen in a MDN article. Based on inspection of your extension's source code, it is plausible that the referenced code is immediately responsible for the error.

The referenced code (in the report here) is a content script that creates an `<img>` element and inserts it in the web page. That means that the image is going to be used in the context of the web page, and therefore the image needs to be web-accessible for it to be shown.

**Comment by MikkCZ** [comment]
Thanks (why did I thought is is about GMail). I was unable to reproduce it right now, but I think I believe where the issue may be. I will investigate later this week a attempt to fix it. I believe it might be theoretically possible to do even without web available resources.

**Comment by MikkCZ** [comment]
I thought about adding the image as `data:` URL, but it would require support from the background page to provide it. Let's do it with `web_accessible_resources`, which is easier.

Thanks for reporting the error. As it does not break any functionality of the add-on, it will go out with the next release when there is more.
