### ISSUE TITLE
Use Pontoon preference for default team

### ISSUE THREAD

**Issue by MikkCZ** [MikkCZ/pontoon-tools#24]
See [bug 1317230](https://bugzilla.mozilla.org/show_bug.cgi?id=1317230) fixed in https://github.com/mozilla/pontoon/pull/683.

**Comment by MikkCZ** [comment]
The change is now deployed in production, time to look at this.

**Comment by flodolo** [comment]
IMO you should also avoid using the Accept-Languages as source. For Italian it gives you it-it, since that's the first one.

Maybe https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n/getUILanguage is better, since the UI locale of a Firefox install will be the one actually available in Pontoon.

**Comment by MikkCZ** [comment]
Good catch, Thank you.
