### ISSUE TITLE
Session is container dependant

### ISSUE THREAD

**Issue by yarons** [MikkCZ/pontoon-tools#71]
### Steps to reproduce

1. Log in to Pontoon in a "Personal" container
2. Switch to "Work" container
3. Switch bask to "Personal" container
4. Somewhere along the way you should start seeing an exclamtion mark (warning/error)

### Expected behavior
I should be able to switch tabs and containers freely while keeping Pontoon Tools running and logged in.

### Actual behavior
Unexpected errors due to tab/container switching.

**Comment by MikkCZ** [comment]
Hi @yarons. At this moment Pontoon Tools do not use any standalone authentication system. Instead, on the background Pontoon Tools periodically refresh data mostly from Pontoon UI with requests containing cookies from your default container and I don't see any easy way to change it at this stage. The correct way to make Pontoon Tools work independent on the default containers cookies would be to use Pontoon API with a separate authentication, which would be hopefully part of the Pontoon.Next project.

@stasm do you already have some draft how would be the authentication done in Pontoon API for getting user specific data?

**Comment by MikkCZ** [comment]
I have actually run into this issue today too. And I finally realized it can really break someones workflow. I need to prioritize this a little and investigate, if WebExtensions can easily choose, what container cookies to include in `fetch()` or AJAX requests.

If not, a plausible option might be to open a hidden tab (in the correct container) and load the data from there. But that should be the last option, as it would involve extensive permissions for containers, tab hiding and maybe more.

**Comment by yarons** [comment]
How about having a dedicated container group or maybe assigning a certain group to it?

**Comment by MikkCZ** [comment]
The problem is that Pontoon Tools should use the same container as the user does for working and signing in to Pontoon web app. So if you use Pontoon in your Personal container and you are not authenticated in any other, Pontoon Tools needs to use cookies from the same Personal container for pulling notifications data.

My general idea is to add an option to the add-on preferences to select which container to use for pulling notifications from Pontoon. If the WebExt API supports to specify container context for requests, just use that container for pulling notifications. If not, the hack with a hidden tab is the only idea I have right now.

**Comment by MikkCZ** [comment]
The only workaround right now is to open Pontoon in the default container (no container) and sign in there. And re-authenticate there once a time after the auth cookie is cleared or invalidated.

**Comment by MikkCZ** [comment]
It seems the [cookies API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies) would allow to read the cookies from the correct cookie store and add add them to the requests programaticaly.

**Comment by MikkCZ** [comment]
This is now released in 3.3.0.
