### ISSUE TITLE
Wrong link for project update notifications, when no team is set

### ISSUE THREAD

**Issue by VishalCR7** [MikkCZ/pontoon-tools#91]
The notification regarding the "`Project` updated with 'x' strings. " in Pontoon tools has the wrong link for the Project which redirects to a 404 page(Eg: https://pontoon.mozilla.org/firefox/)  instead of the project page(Eg: https://pontoon.mozilla.org/projects/firefox/) in Pontoon.

### Expected behavior
The Project link should be `https://pontoon.mozilla.org/projects/slug`

### Actual behavior
The link currently is `https://pontoon.mozilla.org/en-US/firefox/?utm_source=pontoon-tools` which redirects to `https://pontoon.mozilla.org/firefox/` (404 page)

**Comment by MikkCZ** [comment]
Hi Vishal.

When you install Pontoon Tools, it tries o guess the team you belong based
on
- the home page you have selected in Pontoon web app
- the language of your browser

This behaviour you can observe when:
- you are not logged in to Pontoon, or you do not have your home page
changed to your team in Pontoon settings
- and at the same time you are using Firefox in English.

If you want to fix the links, please go to Pontoon Tools settigs and select
the team you are member of. Then the links will go not to `/en-US/firefox`,
nor `/projects/firefox`, but to `/your-team/firefox`, which is the true
expected behaviour.

But you are right that the default behaviour when not team is recognized
should lead you to `/projects/firefox`. Let's try to fix that for the next
release.
--
Michal Stanke

**Comment by MikkCZ** [comment]
Plus the introduction page should ask to choose the team.

**Comment by VishalCR7** [comment]
Thanks @MikkCZ  actually my preferred locale was set to `en-US` which isn't a team name in pontoon. Although I m logged in keeping en-US as my homepage caused it for me. So maybe its better remove en-US from team choices.
